# Generated by Django 5.0.4 on 2024-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0002_category_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('fundation', 'fundacja'), ('ngo', 'organizacja pozarządowa'), ('lokal', 'zbiórka lokalna')], default='fundation')),
                ('categories', models.ManyToManyField(to='MainSite.category')),
            ],
        ),
    ]
