# Generated by Django 5.0.4 on 2024-04-15 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0005_alter_donation_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_donations', to='MainSite.institution'),
        ),
    ]
